# Generated by Django 4.2.9 on 2024-02-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmngmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'subject names'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_address',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
    ]
